AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Pixel Prompt v2 - Focused 4-model image generation with iterative refinement

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Environment Configuration"
        Parameters:
          - Environment
      - Label:
          default: "Flux Configuration (BFL)"
        Parameters:
          - FluxEnabled
          - FluxApiKey
          - FluxModelId
      - Label:
          default: "Recraft Configuration"
        Parameters:
          - RecraftEnabled
          - RecraftApiKey
          - RecraftModelId
      - Label:
          default: "Gemini Configuration (Google)"
        Parameters:
          - GeminiEnabled
          - GeminiApiKey
          - GeminiModelId
      - Label:
          default: "OpenAI Configuration"
        Parameters:
          - OpenaiEnabled
          - OpenaiApiKey
          - OpenaiModelId
      - Label:
          default: "Prompt Enhancement"
        Parameters:
          - PromptModelProvider
          - PromptModelId
          - PromptModelApiKey
      - Label:
          default: "Rate Limiting"
        Parameters:
          - GlobalRateLimit
          - IPRateLimit
          - IPWhitelist

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Environment name for resource tagging

  # Flux (BFL) Configuration
  FluxEnabled:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: Enable Flux model (Black Forest Labs)

  FluxApiKey:
    Type: String
    NoEcho: true
    Default: ""
    Description: BFL API key for Flux models

  FluxModelId:
    Type: String
    Default: "flux-2-pro"
    Description: Flux model ID (e.g., flux-2-pro, flux-pro-1.1, flux-dev)

  # Recraft Configuration
  RecraftEnabled:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: Enable Recraft v3 model

  RecraftApiKey:
    Type: String
    NoEcho: true
    Default: ""
    Description: Recraft API key

  RecraftModelId:
    Type: String
    Default: "recraftv3"
    Description: Recraft model ID

  # Gemini Configuration
  GeminiEnabled:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: Enable Google Gemini model

  GeminiApiKey:
    Type: String
    NoEcho: true
    Default: ""
    Description: Google Gemini API key

  GeminiModelId:
    Type: String
    Default: "gemini-2.5-flash-image"
    Description: Gemini model ID for image generation (e.g., gemini-2.5-flash-image, gemini-3-pro-preview)

  # OpenAI Configuration
  OpenaiEnabled:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: Enable OpenAI gpt-image-1 model

  OpenaiApiKey:
    Type: String
    NoEcho: true
    Default: ""
    Description: OpenAI API key

  OpenaiModelId:
    Type: String
    Default: "gpt-image-1"
    Description: OpenAI image model ID

  # Prompt Enhancement Model
  PromptModelProvider:
    Type: String
    Default: "openai"
    AllowedValues:
      - openai
      - google_gemini
    Description: Provider for prompt enhancement (text/chat model)

  PromptModelId:
    Type: String
    Default: "gpt-4o"
    Description: Model ID for prompt enhancement

  PromptModelApiKey:
    Type: String
    NoEcho: true
    Default: ""
    Description: API key for prompt enhancement model

  # Rate Limiting
  GlobalRateLimit:
    Type: Number
    Default: 1000
    Description: Maximum requests per hour globally

  IPRateLimit:
    Type: Number
    Default: 50
    Description: Maximum requests per day per IP address

  IPWhitelist:
    Type: String
    Default: ""
    Description: Comma-separated IP addresses to bypass rate limits

  # AWS Bedrock Configuration
  BedrockNovaRegion:
    Type: String
    Default: "us-east-1"
    Description: AWS region for Bedrock Nova Canvas (requires us-east-1)

  BedrockSdRegion:
    Type: String
    Default: "us-west-2"
    Description: AWS region for Bedrock Stable Diffusion

Globals:
  Function:
    Tags:
      Project: PixelPromptV2
      Environment: !Ref Environment
      ManagedBy: SAM

Resources:
  PixelPromptFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub '${AWS::StackName}-function'
      Runtime: python3.13
      Handler: lambda_function.lambda_handler
      CodeUri: ./src
      MemorySize: 3008
      Timeout: 900
      ReservedConcurrentExecutions: 10
      Environment:
        Variables:
          # 4 Fixed Models Configuration
          FLUX_ENABLED: !Ref FluxEnabled
          FLUX_API_KEY: !Ref FluxApiKey
          FLUX_MODEL_ID: !Ref FluxModelId
          RECRAFT_ENABLED: !Ref RecraftEnabled
          RECRAFT_API_KEY: !Ref RecraftApiKey
          RECRAFT_MODEL_ID: !Ref RecraftModelId
          GEMINI_ENABLED: !Ref GeminiEnabled
          GEMINI_API_KEY: !Ref GeminiApiKey
          GEMINI_MODEL_ID: !Ref GeminiModelId
          OPENAI_ENABLED: !Ref OpenaiEnabled
          OPENAI_API_KEY: !Ref OpenaiApiKey
          OPENAI_MODEL_ID: !Ref OpenaiModelId
          # Prompt Enhancement
          PROMPT_MODEL_PROVIDER: !Ref PromptModelProvider
          PROMPT_MODEL_ID: !Ref PromptModelId
          PROMPT_MODEL_API_KEY: !Ref PromptModelApiKey
          # Rate Limiting
          GLOBAL_LIMIT: !Ref GlobalRateLimit
          IP_LIMIT: !Ref IPRateLimit
          IP_INCLUDE: !Ref IPWhitelist
          # S3 and CloudFront
          S3_BUCKET: !Ref PixelPromptBucket
          CLOUDFRONT_DOMAIN: !GetAtt CloudFrontDistribution.DomainName
          # Bedrock Regions
          BEDROCK_NOVA_REGION: !Ref BedrockNovaRegion
          BEDROCK_SD_REGION: !Ref BedrockSdRegion
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Sid: S3ReadWriteImages
              Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource:
                - !Sub '${PixelPromptBucket.Arn}/sessions/*'
                - !Sub '${PixelPromptBucket.Arn}/rate-limit/*'
                - !Sub '${PixelPromptBucket.Arn}/gallery/*'
            - Sid: S3ListBucket
              Effect: Allow
              Action: s3:ListBucket
              Resource: !GetAtt PixelPromptBucket.Arn
              Condition:
                StringLike:
                  s3:prefix:
                    - 'sessions/*'
                    - 'gallery/*'
      Events:
        GenerateApi:
          Type: HttpApi
          Properties:
            Path: /generate
            Method: POST
            ApiId: !Ref HttpApi
        IterateApi:
          Type: HttpApi
          Properties:
            Path: /iterate
            Method: POST
            ApiId: !Ref HttpApi
        OutpaintApi:
          Type: HttpApi
          Properties:
            Path: /outpaint
            Method: POST
            ApiId: !Ref HttpApi
        StatusApi:
          Type: HttpApi
          Properties:
            Path: /status/{sessionId}
            Method: GET
            ApiId: !Ref HttpApi
        EnhanceApi:
          Type: HttpApi
          Properties:
            Path: /enhance
            Method: POST
            ApiId: !Ref HttpApi
        GalleryListApi:
          Type: HttpApi
          Properties:
            Path: /gallery/list
            Method: GET
            ApiId: !Ref HttpApi
        GalleryDetailApi:
          Type: HttpApi
          Properties:
            Path: /gallery/{sessionId}
            Method: GET
            ApiId: !Ref HttpApi

  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: Prod
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowHeaders:
          - Content-Type
          - Authorization
          - X-Requested-With
          - X-Correlation-ID
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        MaxAge: 86400
        AllowCredentials: false
      DefaultRouteSettings:
        ThrottlingBurstLimit: 100
        ThrottlingRateLimit: 50

  PixelPromptBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'pixel-prompt-v2-${Environment}-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - '*'
            AllowedMethods:
              - GET
              - HEAD
            AllowedHeaders:
              - '*'
            MaxAge: 3600
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldSessions
            Status: Enabled
            ExpirationInDays: 30
            Prefix: sessions/
    DeletionPolicy: Retain

  CloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub 'OAI for ${AWS::StackName}'

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref PixelPromptBucket
      PolicyDocument:
        Statement:
          - Sid: AllowCloudFrontOAI
            Effect: Allow
            Principal:
              CanonicalUser: !GetAtt CloudFrontOAI.S3CanonicalUserId
            Action: s3:GetObject
            Resource: !Sub '${PixelPromptBucket.Arn}/*'

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub 'CloudFront for ${AWS::StackName}'
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt PixelPromptBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${CloudFrontOAI}'
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          Compress: true
          DefaultTTL: 86400
          MaxTTL: 31536000
        PriceClass: PriceClass_100

  FunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/${PixelPromptFunction}'
      RetentionInDays: 7

  LambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub '${AWS::StackName}-lambda-errors'
      AlarmDescription: Alert on Lambda function errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref PixelPromptFunction
      TreatMissingData: notBreaching

Outputs:
  FunctionName:
    Description: Lambda Function Name
    Value: !Ref PixelPromptFunction

  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/Prod'

  CloudFrontDomain:
    Description: CloudFront distribution domain
    Value: !GetAtt CloudFrontDistribution.DomainName

  S3BucketName:
    Description: S3 bucket name
    Value: !Ref PixelPromptBucket
