#!/usr/bin/env bash
set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Default environment
ENVIRONMENT="${1:-dev}"

# Validate environment
if [[ ! "$ENVIRONMENT" =~ ^(dev|staging|prod)$ ]]; then
    echo -e "${RED}Error: Invalid environment '$ENVIRONMENT'${NC}"
    echo "Usage: $0 [dev|staging|prod]"
    exit 1
fi

echo -e "${GREEN}=== Pixel Prompt Backend Deployment ===${NC}"
echo -e "Environment: ${YELLOW}$ENVIRONMENT${NC}"
echo ""

# Check prerequisites
echo "Checking prerequisites..."

# Check AWS CLI
if ! command -v aws &> /dev/null; then
    echo -e "${RED}Error: AWS CLI not found. Please install: https://aws.amazon.com/cli/${NC}"
    exit 1
fi

# Check SAM CLI
if ! command -v sam &> /dev/null; then
    echo -e "${RED}Error: SAM CLI not found. Please install: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/install-sam-cli.html${NC}"
    exit 1
fi

# Check AWS credentials
if ! aws sts get-caller-identity &> /dev/null; then
    echo -e "${RED}Error: AWS credentials not configured. Run 'aws configure'${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Prerequisites OK${NC}"
echo ""

# Navigate to backend directory
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
BACKEND_DIR="$SCRIPT_DIR/../backend"
FRONTEND_DIR="$SCRIPT_DIR/../frontend"

cd "$BACKEND_DIR"

# Build
echo -e "${YELLOW}Building SAM application...${NC}"
if ! sam build --config-env "$ENVIRONMENT"; then
    echo -e "${RED}Error: SAM build failed${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Build successful${NC}"
echo ""

# Deploy
echo -e "${YELLOW}Deploying to AWS...${NC}"
echo "This may take several minutes..."
echo ""

if ! sam deploy --config-env "$ENVIRONMENT"; then
    echo -e "${RED}Error: SAM deploy failed${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Deployment successful${NC}"
echo ""

# Extract CloudFormation outputs
echo -e "${YELLOW}Extracting CloudFormation outputs...${NC}"

STACK_NAME="pixel-prompt-$ENVIRONMENT"

# Check if jq is available for better JSON parsing
if command -v jq &> /dev/null; then
    # Use jq for reliable JSON parsing
    API_ENDPOINT=$(sam list stack-outputs --stack-name "$STACK_NAME" --output json 2>/dev/null | \
        jq -r '.[] | select(.OutputKey=="ApiEndpoint") | .OutputValue')
    S3_BUCKET=$(sam list stack-outputs --stack-name "$STACK_NAME" --output json 2>/dev/null | \
        jq -r '.[] | select(.OutputKey=="S3BucketName") | .OutputValue')
    CLOUDFRONT_DOMAIN=$(sam list stack-outputs --stack-name "$STACK_NAME" --output json 2>/dev/null | \
        jq -r '.[] | select(.OutputKey=="CloudFrontDomain") | .OutputValue')
else
    # Fallback to awk if jq not available
    echo -e "${YELLOW}Note: jq not found, using awk (install jq for better reliability)${NC}"
    API_ENDPOINT=$(sam list stack-outputs --stack-name "$STACK_NAME" 2>/dev/null | \
        grep "ApiEndpoint" | awk '{print $2}')
    S3_BUCKET=$(sam list stack-outputs --stack-name "$STACK_NAME" 2>/dev/null | \
        grep "S3BucketName" | awk '{print $2}')
    CLOUDFRONT_DOMAIN=$(sam list stack-outputs --stack-name "$STACK_NAME" 2>/dev/null | \
        grep "CloudFrontDomain" | awk '{print $2}')
fi

# Verify outputs were extracted
if [ -z "$API_ENDPOINT" ]; then
    echo -e "${RED}Error: Could not extract API endpoint from CloudFormation outputs${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Outputs extracted${NC}"
echo ""

# Generate frontend .env file
echo -e "${YELLOW}Generating frontend .env file...${NC}"

ENV_FILE="$FRONTEND_DIR/.env"

# Create .env file
cat > "$ENV_FILE" << EOF
# Auto-generated by deploy.sh on $(date)
# Environment: $ENVIRONMENT
# Stack: $STACK_NAME

# Backend API endpoint
VITE_API_ENDPOINT=$API_ENDPOINT

# CloudFront domain for image delivery
VITE_CLOUDFRONT_DOMAIN=$CLOUDFRONT_DOMAIN

# S3 bucket name (for reference)
VITE_S3_BUCKET=$S3_BUCKET

# Environment identifier
VITE_ENVIRONMENT=$ENVIRONMENT
EOF

echo -e "${GREEN}✓ Frontend .env file created at: $ENV_FILE${NC}"
echo ""

# Display .env contents
echo -e "${YELLOW}Frontend environment variables:${NC}"
cat "$ENV_FILE"
echo ""

# Verify API endpoint with health check
echo -e "${YELLOW}Verifying API endpoint...${NC}"

# Test the API with a simple request (try /gallery/list as it should work without auth)
HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" "$API_ENDPOINT/gallery/list" 2>/dev/null || echo "000")

if [ "$HTTP_STATUS" = "200" ]; then
    echo -e "${GREEN}✓ API endpoint is responding (HTTP 200)${NC}"
elif [ "$HTTP_STATUS" = "404" ]; then
    echo -e "${GREEN}✓ API endpoint is accessible (HTTP 404 - no galleries yet, this is expected)${NC}"
else
    echo -e "${YELLOW}⚠ API endpoint returned HTTP $HTTP_STATUS${NC}"
    echo -e "${YELLOW}  This might be expected if CloudFront is still deploying (~15 min)${NC}"
fi
echo ""

# Summary
echo -e "${GREEN}=== Deployment Complete ===${NC}"
echo ""
echo -e "Stack Name:        ${YELLOW}$STACK_NAME${NC}"
echo -e "API Endpoint:      ${YELLOW}$API_ENDPOINT${NC}"
echo -e "CloudFront Domain: ${YELLOW}$CLOUDFRONT_DOMAIN${NC}"
echo -e "S3 Bucket:         ${YELLOW}$S3_BUCKET${NC}"
echo ""
echo -e "${GREEN}Next steps:${NC}"
echo "1. Frontend .env has been created at: $ENV_FILE"
echo "2. Build frontend: cd frontend && npm run build"
echo "3. Preview frontend: cd frontend && npm run preview"
echo "4. Deploy frontend to your hosting platform"
echo ""
echo -e "${YELLOW}Note: CloudFront distribution may take up to 15 minutes to fully deploy${NC}"
echo ""
